### ISSUE TITLE
Erreur installation core Home Assistant 2022.9.7

### ISSUE THREAD

**Issue by youssef59600** [mawaqit/home-assistant#26]
Bonjour,

je viens de faire l'installation de Mawaqit sur un HASSOS version : 

Home Assistant 2022.9.7
Supervisor 2022.09.1
Operating System 9.0
Interface utilisateur : 20220907.2 - latest

Malgré plusieurs essaie j'ai toujours l'erreur suivantes :  

Cette erreur provient d'une intégration personnalisée

Logger: homeassistant.config_entries
Source: custom_components/mawaqit/__init__.py:286
Integration: mawaqit
First occurred: 22:57:48 (1 occurrences)
Last logged: 22:57:48

Error setting up entry Mawaqit for mawaqit_prayer_times
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/mawaqit/__init__.py", line 285, in async_setup
    await self.hass.async_add_executor_job(self.get_new_prayer_times)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mawaqit/__init__.py", line 190, in get_new_prayer_times
    n = text_file.write(str(calc.fetch_prayer_times()))
  File "/usr/local/lib/python3.10/site-packages/mawaqit_times_calculator/pray_times_calculator.py", line 94, in fetch_prayer_times
    s1 = response.json()["times"][0]
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mawaqit/__init__.py", line 72, in async_setup_entry
    if not await client.async_setup():
  File "/config/custom_components/mawaqit/__init__.py", line 286, in async_setup
    except (exceptions.InvalidResponseError, ConnError) as err:
NameError: name 'exceptions' is not defined

![image](https://user-images.githubusercontent.com/67575391/193140939-6ef1a262-8141-41fa-848d-36a96863cfc1.png)

Pouvez-vous svp m'aider sur ce problème ?

BArkallah o fikoum

**Comment by youssef59600** [comment]
Alikoum Salam Yacine,

Barkallah o fik pour ce retour. J'ai éssayé la nouvelle version et j'arrive
bien à l'installer mais au moment de choisir la mosquée je rencontre une
erreur :

[image: image.png]


Cette erreur provient d'une intégration personnalisée

Logger: aiohttp.server
Source: custom_components/mawaqit/mawaqit.py:154
Integration: Mawaqit
First occurred: 09:43:48 (1 occurrences)
Last logged: 09:43:48

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py",
line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line
504, in _handle
    resp = await handler(request)
  File
"/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line
117, in impl
    return await handler(request)
  File
"/usr/src/homeassistant/homeassistant/components/http/security_filter.py",
line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py",
line 100, in forwarded_middleware
    return await handler(request)
  File
"/usr/src/homeassistant/homeassistant/components/http/request_context.py",
line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line
82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line
236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line
136, in handle
    result = await result
  File
"/usr/src/homeassistant/homeassistant/components/config/config_entries.py",
line 178, in post
    return await super().post(request, flow_id)
  File
"/usr/src/homeassistant/homeassistant/components/http/data_validator.py",
line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py",
line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 280,
in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367,
in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/mawaqit/config_flow.py", line 134, in
async_step_mosques
    db = await self.fetch_prayer_times(
  File "/config/custom_components/mawaqit/config_flow.py", line 253, in
fetch_prayer_times
    db = await  client.fetch_prayer_times()
  File "/config/custom_components/mawaqit/mawaqit.py", line 154, in
fetch_prayer_times
    raise NotAuthenticatedException
custom_components.mawaqit.mawaqit.NotAuthenticatedException



Logger: homeassistant
Source: runner.py:119
First occurred: 09:43:48 (2 occurrences)
Last logged: 09:43:48

   - Error doing job: Unclosed client session
   - Error doing job: Unclosed connector



Tu a une idée de ce qui peut causer cette erreur ?

Barkallah o fik, pour ton aide.

Cdlt,

**Comment by youssef59600** [comment]
Salam,

une idée stp sur la cause de cette erreur ?

Merci

**Comment by youssef59600** [comment]
Salam Alikoum,

avez vous svp une idée d'ou peut venir l'erreur ?

Merci
