### ISSUE TITLE
Error After installation mawaqit V2

### ISSUE THREAD

**Issue by youssef59600** [mawaqit/home-assistant#27]
Hello,

I have the following error after the installation of mawaqit v2. Can you please help me on the resolution of this issue ?

Logger: homeassistant.config_entries
Source: custom_components/mawaqit/__init__.py:201
Integration: Mawaqit
First occurred: 14:42:41 (1 occurrences)
Last logged: 14:42:41

Error setting up entry Mawaqit for mawaqit
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mawaqit/__init__.py", line 87, in async_setup_entry
    if not await client.async_setup():
  File "/config/custom_components/mawaqit/__init__.py", line 360, in async_setup
    await self.hass.async_add_executor_job(self.get_new_prayer_times)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mawaqit/__init__.py", line 201, in get_new_prayer_times
    day_times_tomorrow = month_times[str(index_day+1)]
KeyError: '32'

Thks

**Comment by youssef59600** [comment]
I did the installation again today ( 01/11/2022) and no issu anymore. Seem to be a bug with the day I was triying to install yesterday ( 31th days of the mounth).

**Comment by Lainami** [comment]
Bonjour, je n'arrive pas à obtenir une carte détaillée de la mosquée choisir ( adresse, numero de téléphone, ... etc) comme sur la pièce jointe n° 1. Pourriez vous m'indiquer comment y remédier ? merci d'avance.

**Comment by soofiane84** [comment]
Bonjour, 

J'ai le même problème aujourd'hui le 30/04, le dernier jour du mois. 

```
Logger: homeassistant.config_entries
Source: custom_components/mawaqit/__init__.py:201
Integration: Mawaqit
First occurred: 03:02:37 (2 occurrences)
Last logged: 05:15:46

Error setting up entry Mawaqit for mawaqit
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mawaqit/__init__.py", line 87, in async_setup_entry
    if not await client.async_setup():
  File "/config/custom_components/mawaqit/__init__.py", line 360, in async_setup
    await self.hass.async_add_executor_job(self.get_new_prayer_times)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mawaqit/__init__.py", line 201, in get_new_prayer_times
    day_times_tomorrow = month_times[str(index_day+1)]
KeyError: '31'
```
