### ISSUE TITLE
After update to V3 Mawaqit is not working anymore 

### ISSUE THREAD

**Issue by ahmedbarakat83** [mawaqit/home-assistant#75]
Al Salam Alykom brothers,
HA 2024.10.4

I updated today to v3 and now the integration is not 
loading any more and I get the error below.

Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 12:01:49 PM (1 occurrences)
Last logged: 12:01:49 PM

Error setting up entry MAWAQIT - Al-Rahma Moschee for mawaqit
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mawaqit/__init__.py", line 105, in async_setup_entry
    if not await client.async_setup():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mawaqit/__init__.py", line 468, in async_setup
    await self.get_new_prayer_times()
  File "/config/custom_components/mawaqit/__init__.py", line 186, in get_new_prayer_times
    await utils.update_my_mosque_data_files(
  File "/config/custom_components/mawaqit/utils.py", line 252, in update_my_mosque_data_files
    mosque_id = my_mosque["uuid"]
                ~~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

Thanks in advance for your support.

Best Regards,
Ahmed

**Comment by Yeyvo** [comment]
Assalam alaykoum brother, how did you proceed with the update? Did you delete all Mawaqit-related files and set up the integration from scratch?
I'm unable to reproduce the issue on my end, so any detailed steps or instructions you followed would be incredibly helpful. 
Also, could you please provide us with the debug logs? You can enable them in the Mawaqit integration configuration. However, be careful not to include your MAWAQIT_API_KEY or any personal data. Once you download the logs, you can open the file, search for MAWAQIT_API_KEY, and remove all occurrences before sharing.
Thank you!

**Comment by ahmedbarakat83** [comment]
Walaykom Al Salam.

I have installed it first time using HACS, so I got yesterday a notification in HA that there is an available update.
So I did the install update from HA system.

**Comment by ahmedbarakat83** [comment]
I did restore a backup before the update now and went back to v2.0 and it is working perfect.

Kazak Allah Kol Khayer

**Comment by Yeyvo** [comment]
Salam ahmed, 
Ameen to your duaa! Just to check, have you tried clearing your Mawaqit integration settings after updating the integration? Sometimes, resetting the integration can resolve similar issues after an update.

Let us know if this helps, or if the problem persists – we're here to help troubleshoot further!

May Allah bless you
